### ISSUE TITLE
More informations and actions

### ISSUE THREAD

**Issue by JeedHome44** [epenet/hassRenaultZE#26] opened 2020-04-07 08:56 UTC
Can we have this informations:

- remaining time
- load power
- calendar status
- preconditioning state

And can we also have these actions:

- ignition of preconditioning
- calendar activation
- calendar deactivation

It's possible? With the Jeedom pluggin, before, i have this informations and actions :)

**Comment by epenet** [comment] 2020-04-08 20:38
Hi,
Welcome to Home Assistant.
I think that the Jeedom plugin is also based on pyze, so it shouldn't be too difficult to add. The issue is just finding the time...

Of course, if you know Python, then I always welcome PRs.

**Comment by JeedHome44** [comment] 2020-04-08 20:46
I would like to know how to program but I don't know at all.  on Jeedom, the plugin stopped working at the same time as yours but it already offered all the info and actions.

**Comment by JeedHome44** [comment] 2020-04-09 08:25
Hello,

I was able to download the ZE plugin files on Jeedom. Can I send them to you by email?

**Comment by epenet** [comment] 2020-04-09 08:37
Sure

**Comment by JeedHome44** [comment] 2020-04-09 08:43
your mail please :)

**Comment by JeedHome44** [comment] 2020-04-09 08:46
https://1fichier.com/?2yublpyqaqpi6i7ti099

say me if it's ok ;)

**Comment by epenet** [comment] 2020-04-09 08:54
I have it, but I'm still not sure when I'll have time to take a look...

**Comment by johan12345** [comment] 2020-04-24 10:56
> Can we have this informations:
> 
> remaining time
> load power
> calendar status
> preconditioning state

these should now be available -> see #27

**Comment by JeedHome44** [comment] 2020-04-24 11:04
> > Can we have this informations:
> > remaining time
> > load power
> > calendar status
> > preconditioning state
> 
> these should now be available -> see #27

Thank you!
how to do?  just download the file and replace it on HA?

**Comment by johan12345** [comment] 2020-04-24 11:05
Yes, that should work. After replacing the file, a restart of HA is probably necessary.

**Comment by JeedHome44** [comment] 2020-04-24 11:33
it's work! i wait now this action ;)

ignition of preconditioning
calendar activation
calendar deactivation

if that it possible, it will be great!

**Comment by JeedHome44** [comment] 2020-04-24 11:46
> Yes, that should work. After replacing the file, a restart of HA is probably necessary.

sorry but where is the calendar status now? i don't find it in my HA after the update ;)

**Comment by epenet** [comment] 2020-04-24 12:53
charge_mode I've added in PR #28
"plug_status" is a description built from "plugged" sensor
"charge_status"  is a description built from "plugged" and "charging" sensors

**Comment by JeedHome44** [comment] 2020-04-24 12:59
thank you but i haven't "charge_mode"

"charging_power" does not go back to 0 when the charge is finished. is this normal?

**Comment by JeedHome44** [comment] 2020-04-24 13:02
charging_remaining_time does not appear in attributes when charging is in progress

thank you for your work

**Comment by johan12345** [comment] 2020-04-24 13:07
> thank you but i haven't "charge_mode"

The Pull request has not yet been merged by @epenet 

> "charging_power" does not go back to 0 when the charge is finished. is this normal?

I have also noticed this. Probably my changes in https://github.com/epenet/hassRenaultZE/pull/29 will help

> charging_remaining_time does not appear in attributes when charging is in progress

It did appear for me. Can you check if it appears when running [PyZE](https://github.com/jamesremuscat/pyze) directly? If not, it probably depends on the type of vehicle and/or software version.

**Comment by epenet** [comment] 2020-04-24 13:15
@JeedHome44 can you grab latest file from the [issue_26 branch](https://github.com/epenet/hassRenaultZE/tree/issue_26)?

**Comment by JeedHome44** [comment] 2020-04-24 13:18
i just do changes. my HA restart and i will test it ;)

**Comment by JeedHome44** [comment] 2020-04-24 13:19
now i have change mode = schedule_mode! Great job! Thank you so much!
and i have charging power = 0 and charging remaining time = -

thank you so much :)

**Comment by JeedHome44** [comment] 2020-04-24 13:41
only the actions are missing and it will be perfect

**Comment by JeedHome44** [comment] 2020-04-26 09:00
Hello! I just test a charge and i have remaining time and charging power. All informations work!

It’s possible to have actions please?

**Closed** 2020-05-08 12:30 UTC
